# Generated by Django 4.1.7 on 2023-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LINE_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
