# Generated by Django 4.1.7 on 2023-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LINE_bot_app', '0002_user_info_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='hute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=50)),
                ('humidity', models.CharField(blank=True, max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('mdt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
