# Generated by Django 4.1.7 on 2023-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LINE_bot_app', '0003_hute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hute',
            name='num',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hute',
            name='temperature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
