# Generated by Django 4.1.7 on 2023-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LINE_bot_app", "0004_alter_hute_num_alter_hute_temperature"),
    ]

    operations = [
        migrations.CreateModel(
            name="medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
                ("interval", models.CharField(blank=True, max_length=255)),
                ("before_meal", models.CharField(blank=True, max_length=255)),
                ("after_meal", models.CharField(blank=True, max_length=255)),
                ("before_bedtime", models.CharField(blank=True, max_length=255)),
                ("mdt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
