# Generated by Django 4.1.7 on 2023-12-23 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("LINE_bot_app", "0005_medicine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="image/")),
                ("upload_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="medicine",
            name="num",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="medicine",
            name="uid",
            field=models.CharField(default="", max_length=50),
        ),
    ]
